### ISSUE TITLE
websocket.send(msgtosend) is not giving any response. 

### ISSUE THREAD

**Issue by SaminaZahidFulda** [eclipse/ditto-examples#18]
Here I am trying to send message to thing "SmartCoffee" but its not responding with any message.

var websocket = new WebSocket('ws://demo1:demo@ditto.eclipse.org/ws/2');
        websocket.onmessage= function(message) {
            console.log('received message data: ' +  message.data);
        };
        websocket.onopen = function(ws) {
            // register for receiving messages
            console.log('Open');
            // websocket.send('START-SEND-MESSAGES');
            var msg = {
                        "topic": "org.eclipse.ditto/smartcoffee/things/live/messages/ask",
                        "headers": {
                            "content-type": "text/plain",
                            "correlation-id": "2215ea11-dbe5-413e-a783-24ec9c9f9619"
                        },
                        "path": "/inbox/messages/ask",
                        "value": "Hey, how are you?"
                    }
            var msgtosend =    JSON.stringify(msg);
            **websocket.send(msgtosend);**
            console.log(msgtosend);
        };

**Comment by ffendt** [comment]
Hi there,

what means, its not responding any message? Are you seeing any logs?

Can you see any error logs when also adding an `websocket.onerror` event listener?

Regards

**Comment by jufickel-b** [comment]
Closed due to inactivity.
