### ISSUE TITLE
Ditto connection lost on reloading the page 

### ISSUE THREAD

**Issue by SaminaZahidFulda** [eclipse/ditto-examples#19]
![image](https://user-images.githubusercontent.com/38786093/64429929-64c90900-d0b7-11e9-9b0f-53732c72b571.png)

How can I maintain the session of ditto?

**Comment by ffendt** [comment]
Hi there, I don't think it will be possible to maintain a connection to Ditto when reloading the page. Why do you need it?

**Comment by SaminaZahidFulda** [comment]
I am building UI for ditto, where I have multiple pages, therefore, have to maintain session as persistent. But I have gone through the documentation but did not find it. @ffendt

**Comment by ffendt** [comment]
Usually you would build a Single Page Application (SPA), so there is no real page reload and you can keep your connection to Ditto as long as the user stays on the page. Afaik most of the state-of-the-art UI frameworks are SPA-frameworks (e.g. Angular, React, Vue, ...).

**Comment by ffendt** [comment]
I'm closing this issue as this seems to be a general UI development question and not an issue with the Ditto examples. The Eclipse Ditto project also provides a [gitter](https://gitter.im/eclipse/ditto#) chat which would probably fit better for questions regarding this topic.
