### ISSUE TITLE
Module 'websocket' has no attribute 'WebSocketApp'

### ISSUE THREAD

**Issue by danielanghell** [eclipse/ditto-examples#30]
I am writting this because I cannot establish a connection through websocket from my raspi 4. 
I don't have the GrovePi+, nor the sensors obviously. I have also changed the grovepi library into grovepi_mock, since it's written to do when you want to start the example without GrovePi. 
I do have the grovepi modules installed and also the websocket-client module. The raspi is running on the same network as the Ditto instance. The thing is also registered.
![2020-03-24-190817_1920x1080_scrot](https://user-images.githubusercontent.com/48117672/77455778-f8b7b380-6e02-11ea-9979-eea636f8f94d.png)

**Comment by thjaeckle** [comment]
Did you try that solution?
https://stackoverflow.com/questions/42141689/attributeerror-module-object-has-no-attribute-websocketapp

**Comment by danielanghell** [comment]
I have just tried and it still doesn't work. 
Does it have to do anything with the fact that I didn't create a raspberry user? Instead I am using the ditto:ditto user. I have also modified in the raspbery_thing.py according to these credentials.
If you have any suggestion, it's really well-come since I am not so familiar with Ditto project.

**Comment by ffendt** [comment]
Maybe it helps [uninstalling and installing](https://stackoverflow.com/a/53444938/11534810) the websocket-client instead of just installing it over again. Somehow the websocket import must have a problem.

**Comment by danielanghell** [comment]
I have uninstalled both of them, websocket and websocket client, and then just installed the websocket-client. Still doesn’t work somehow. :(

**Comment by danielanghell** [comment]
I have mistakenly installed the websocket using pip3 and I have also forgotten to use the same uninstall command. Now it works! Thank you so much for your support!
