### ISSUE TITLE
Can't see Captcha Image

### ISSUE THREAD

**Issue by danielanghell** [eclipse/ditto-examples#31]
Regarding the SmartCoffeeMachine, I am trying to brew a coffee but it doesn't happen because it doesn't pop up any captcha code. Obviously, I have created the twin and I have also connected to it. Heating up water tank and the reverse action work fine.
I can see that the PUT request is sent and also de JSON file is arriving at the machine, but since I cannot solve any captcha, I receive a 408 Request Timeout.
![Screenshot from 2020-03-29 06-19-38](https://user-images.githubusercontent.com/48117672/77846684-c4871e80-7185-11ea-8980-ef44dc1f4436.png)

**Comment by ffendt** [comment]
Hi @danielanghell, 
can you please check if the browser console (F12) is printing any errors after sending the "Go make me a coffee" message is sent? This sounds like it might be a JavaScript bug in the example.

**Comment by danielanghell** [comment]
Here is the error highlighted while trying to "make a coffee".
![Screenshot from 2020-03-30 16-30-15](https://user-images.githubusercontent.com/48117672/77959119-18882500-72a4-11ea-9877-f65b99ea1114.png)

**Comment by ffendt** [comment]
Hi @danielanghell 
sorry for letting you wait. The javascript app tried to parse the received JSON twice (which I fixed with #34). Thanks for letting us know about this bug!
Can you please pull the examples again and try if it works now on your side, too?

**Comment by danielanghell** [comment]
Hello @ffendt,
thank you for your help and kindness. Now it works fine!
