### ISSUE TITLE
payload mapping error 

### ISSUE THREAD

**Issue by saunakasansol94** [eclipse/ditto-examples#5]
hello, am new to eclipse ditto and Eclipse Mosquitto. I have followed the following process to create a bidirectional MQTT.  https://github.com/eclipse/ditto-examples/tree/master/mqtt-bidirectional
Am getting a Payload mapping error .
the code to create MQTT Connection is 
`{
    "targetActorSelection": "/system/sharding/connection",
    "headers": {
    	"aggregate": false
    },
    "piggybackCommand": {
        "type": "connectivity.commands:createConnection",
        "connection": {
            "id": "mqtt-example-connection-1234",
            "connectionType": "mqtt",
            "connectionStatus": "open",
            "failoverEnabled": true,
            "uri": "tcp://localhost:1883",
            "sources": [{
                "addresses": ["ditto-tutorial/#"],
                "authorizationContext": ["nginx:ditto"],
                "qos": 0,
                "filters": []
            }],
            "targets": [{
                "address": "ditto-tutorial/{{ thing:id }}",
                "topics": [
                "_/_/things/twin/events",
                "_/_/things/live/messages"
                ],
                "authorizationContext": ["nginx:ditto"],
                "qos": 0
            }]
        }
    }
}`
the responce while creating MQTT Connection is 
![image](https://user-images.githubusercontent.com/35859990/50753748-05410200-1279-11e9-914a-29dcd45b7dfb.png)

Code for creating  payload mapping is as follow 
`{
    "targetActorSelection": "/system/sharding/connection",
    "headers": {
    	"aggregate": false
    },
    "piggybackCommand": {
        "type": "connectivity.commands:modifyConnection",
        "connection": {
            "id": "mqtt-example-connection-1234",
            "connectionType": "mqtt",
            "connectionStatus": "open",
            "failoverEnabled": true,
            "uri": "tcp://localhost:1883",
            "sources": [{
                "addresses": ["ditto-tutorial/#"],
                "authorizationContext": ["nginx:ditto"],
                "qos": 0,
                "filters": []
            }],
            "targets": [{
                "address": "ditto-tutorial/{{ thing:id }}",
                "topics": [
                "_/_/things/twin/events",
                "_/_/things/live/messages"
                ],
                "authorizationContext": ["nginx:ditto"],
                "qos": 0
            }],
            "mappingContext": {
                "mappingEngine": "JavaScript",
                "options": {
                    "incomingScript": "function mapToDittoProtocolMsg(headers, textPayload, bytePayload, contentType) {const jsonString = String.fromCharCode.apply(null, new Uint8Array(bytePayload));const jsonData = JSON.parse(jsonString); const thingId = jsonData.thingId; const value = { temp_sensor: { properties: { value: jsonData.temp } },altitude:        {            properties:            {                value: jsonData.alt            }        }    };    return Ditto.buildDittoProtocolMsg('my.test', thingId, 'things', 'twin', 'commands', 'modify', '/features', headers, value);}"
                }
            }
        }
    }
}`
the responce from payload mapping is : 
![image](https://user-images.githubusercontent.com/35859990/50753716-e80c3380-1278-11e9-85f3-f6bf9d4402b0.png)

Can you suggest me what to do?

**Comment by ffendt** [comment]
Hi @saunakasansol94,
can i close this issue as the same issue is processed in [Ditto issue 310](https://github.com/eclipse/ditto/issues/310)?
