### ISSUE TITLE
Payload mapping  connection failed 

### ISSUE THREAD

**Issue by saunakasansol94** [eclipse/ditto-examples#6]
Am using the following step to create an MQTT connection and payload mapping.
[https://github.com/eclipse/ditto-examples/tree/master/mqtt-bidirectional]

when I am Posting the following code in the localhost using postman am getting the error 
"The Connection with ID 'mqtt-example-connection-123' failed to connect." 
the code to post is as follow: 
 "POST" URI: `http://localhost:8080/devops/piggyback/connectivity?timeout=10000`
Body
`{
    "targetActorSelection": "/system/sharding/connection",
    "headers": {
    	"aggregate": false
    },
    "piggybackCommand": {
        "type": "connectivity.commands:modifyConnection",
        "connection": {
            "id": "mqtt-example-connection-123",
            "name": "saunak2",
            "connectionType": "mqtt",
            "connectionStatus": "open",
            "failoverEnabled": true,
            "uri": "tcp://test.mosquitto.org:1883",
            "sources": [{
                "addresses": ["ditto-tutorial/#"],
                "authorizationContext": ["nginx:ditto"],
                "qos": 0,
                "filters": []
            }],
            "targets": [{
                "address": "ditto-tutorial/{{ thing:id }}",
                "topics": [
                "_/_/things/twin/events",
                "_/_/things/live/messages"
                ],
                "authorizationContext": ["nginx:ditto"],
                "qos": 0
            }],
            "mappingContext": {
                "mappingEngine": "JavaScript",
                "options": {
                    "incomingScript": "function mapToDittoProtocolMsg(headers, textPayload, bytePayload, contentType) {   const jsonString = String.fromCharCode.apply(null, new Uint8Array(bytePayload));  const jsonData = JSON.parse(jsonString); const thingId = 'my.test:octopus' const value = {  temp_sensor: {         properties: {  value: 30.67, }   },   altitude: {  properties: {   value: 360.341,   } }   };    return Ditto.buildDittoProtocolMsg(  'my.test', // your namespace   thingId,  'things', // we deal with a thing  'twin', // we want to update the twin   'commands', // create a command to update the twin  'modify', // modify the twin  '/features', // modify all features at once     headers,   value );}"
                }
            }
        }
    }
}`
the output of the code 
![image](https://user-images.githubusercontent.com/35859990/50759252-7ccb5d00-128a-11e9-9ef2-f3c95ce6a4d6.png)
Suggest me what can be the problem?

**Comment by ffendt** [comment]
Hi @saunakasansol94,
can i close this issue as the same issue is processed in [Ditto issue 310](https://github.com/eclipse/ditto/issues/310)?
