### ISSUE TITLE
Can't create a new policy (400 Bad Request)

### ISSUE THREAD

**Issue by BobOntario** [eclipse/ditto-examples#7]
Tried to repeat this example, but can't create a policy with the following commands:

curl -X put 'http://localhost:8080/api/2/policies/my.test:policy' -u 'ditto:ditto' -H 'Content-Type: application/json' -d '{
    "entries": {
        "owner": {
            "subjects": {
                "nginx:ditto": {
                    "type": "nginx basic auth user"
                }
            },
            "resources": {
                "thing:/": {
                    "grant": [
                        "READ","WRITE"
                    ],
                    "revoke": []
                },
                "policy:/": {
                    "grant": [
                        "READ","WRITE"
                    ],
                    "revoke": []
                },
                "message:/": {
                    "grant": [
                        "READ","WRITE"
                    ],
                    "revoke": []
                }
            }
        }
    }
}'

Error message is as below:
<html>
<head><title>400 Bad Request</title></head>
<body bgcolor="white">
<center><h1>400 Bad Request</h1></center>
<hr><center>nginx/1.13.12</center>
</body>
</html>

**Comment by ffendt** [comment]
Hi @BobOntario,

are you trying to repeat the mqtt-bidirectional example or another example?

How did you start Ditto locally?

The error response you posted is an error response coming from nginx, meaning the request didn't even reach the gateway service in Ditto. Therefore I assume there is a problem with the nginx configuration. Could you have a look at the nginx logs?

**Comment by BobOntario** [comment]
@ffendt 

Yes, I did repeat  mqtt-bidirectional and "hello world -  https://www.eclipse.org/ditto/intro-hello-world.html" examples with the same environment.  The interesting thing is that "Hello world" is working, but mqtt-bidirectional is not working.  I found that "hello world one is using API version 1 while Mqtt using API Version 2.   I don't know why?

**Comment by BobOntario** [comment]
Where can I find the nginx logs?

**Comment by ffendt** [comment]
Hi @BobOntario,

the difference between API 1 and 2 is basically the different authorization concepts ([ACLs](https://www.eclipse.org/ditto/basic-acl.html) vs. [Policies](https://www.eclipse.org/ditto/basic-policy.html)).

When having started Ditto locally using `docker-compose`, you can use the command `docker-compose logs nginx` to have a look at the logs of the local nginx instance. `docker-compose` also provides other useful commands which are documented in the [docker docs](https://docs.docker.com/compose/reference/).

I tried the example and had the exact same problem you experienced. I noticed that the curl commands in the mqtt-bidirectional example are using `-X put`, but should use `-X PUT`. Can you verify that the commands will work when using an uppercase `PUT` instead of lowercase? I'll update the documentation accordingly.

Best regards

**Comment by BobOntario** [comment]
@ffendt you are right. I changed "put" to "PUT" -worked in one machine.  But I tried other machine, didn't work at all.  Always got bad gateway. Below is logs file.  Feeling not stable. Tried to rebuild ditto, also got a probelm, see #346
 
![logs](https://user-images.githubusercontent.com/27965673/53851607-2f6b2380-3f8d-11e9-9f71-fc254ee010c6.PNG)

**Comment by ffendt** [comment]
Hi @BobOntario,

could you please provide me with some more information?
* What did you try on another machine? The complete mqtt-bidirectional example? 
* What kind of machine?
* What says the log of the Dittos gateway service? (`docker-compose logs gateway`)
* Are all services running? (`docker-compose ps`)

**Comment by BobOntario** [comment]
I used ubuntu 18.04 under Virtual machine with image from docker hub (0.8.0), I have problem with gateway, logs message is about connection refused.  I suspect proxy issue.

I changed to cloud server ubuntu 16.04 and built image in local. I have no problem to follow instructions to create policy and thing.   When I tried to build a connection to mqtt with following code, I got an error say "mqtt-example-connection-123' could not be found. any clues?

{"?":{"?":{"type":"devops.responses:errorResponse","status":404,"serviceName":null,"instance":null,"payload":{"status":404,"error":"connectivity:connection.notfound","message":"The Connection with ID 'mqtt-example-connection-123' could not be found.","description":"Check if the ID of your requested Connection was correct."}}}}

-----------------------------------------------
curl -X POST 'http://localhost:8080/devops/piggyback/connectivity?timeout=10000' -u 'devops:foobar' -H 'Content-Type: application/json' -d '{

 "targetActorSelection": "/system/sharding/connection",
    "headers": {
    	"aggregate": false
    },
    "piggybackCommand": {
        "type": "connectivity.commands:modifyConnection",
        "connection": {
            "id": "mqtt-example-connection-123",
            "connectionType": "mqtt",
            "connectionStatus": "open",
            "failoverEnabled": true,
            "uri": "tcp://test.mosquitto.org:1883",
            "sources": [{
                "addresses": ["ditto-tutorial/#"],
                "authorizationContext": ["nginx:ditto"],
                "qos": 0,
                "filters": []
            }],
            "targets": [{
                "address": "ditto-tutorial/{{ thing:id }}",
                "topics": [
                "_/_/things/twin/events",
                "_/_/things/live/messages"
                ],
                "authorizationContext": ["nginx:ditto"],
                "qos": 0
            }],
            "mappingContext": {
                "mappingEngine": "JavaScript",
                "options": {
                    "incomingScript": "function mapToDittoProtocolMsg(headers, textPayload, bytePayload, contentType) {const jsonString = String.fromCharCode.apply(null, new Uint8Array(bytePayload));const jsonData = JSON.parse(jsonString); const thingId = jsonData.thingId; const value = { temp_sensor: { properties: { value: jsonData.temp } },altitude:        {            properties:            {                value: jsonData.alt            }        }    };    return Ditto.buildDittoProtocolMsg('my.test', thingId, 'things', 'twin', 'commands', 'modify', '/features', headers, value);}"
                }
            }
        }
    }
}'

**Comment by BobOntario** [comment]
![connection](https://user-images.githubusercontent.com/27965673/53995370-dde4a500-4102-11e9-8a3f-554ec23dc60a.PNG)

**Comment by BobOntario** [comment]
*### [error] 7#7: 15 open() "/etc/nginx/html/index.php" failed (2: No such file or directory),

I can't see this file too. It should be in the container.

![no index](https://user-images.githubusercontent.com/27965673/54001557-a7665480-4119-11e9-9356-5b6fc9e3f1dd.PNG)

**Comment by thjaeckle** [comment]
Regarding the creation of the connection:
That is an error in our example, sorry for that - the example uses a `"type": "connectivity.commands:modifyConnection"` which only works when the connection already has been created.
Please change that to `"type": "connectivity.commands:createConnection",` instead, as also documented in: https://www.eclipse.org/ditto/connectivity-manage-connections.html#create-connection

**Comment by thjaeckle** [comment]
Towards your "index.php" problem:
You deployed Ditto on a public server, didn't you?
Seems like someone is running a script trying to get into your server (a.k.a. "hack" your server) by trying to execute a command via PHP. That won't succeed as there is no index.php and no PHP interpreter in the nginx.

So nothing wrong with Ditto here, just the normal script kiddies "exploring" security issues.

**Comment by BobOntario** [comment]
In Front-end section

### **_The following command is wrong?  should be "cd iot-frontend"_**
$ cd iot-solution

### **_The following command is wrong? should miss something ("command")_**

$ npm -i

**### _Running Dev-Server (with hot reloading):_**

// serving the ui using yarn
$ yarn serve

_**### Can't find "serve" in the following command**_ 
// or serving the ui using npm
$ npm run serve

**Comment by BobOntario** [comment]
other question. in your example of connection, you connect to mqtt at "tcp://test.mosquitto.org:1883",  if i want to connect to localhost mqtt, whether I just change to "tcp://localhost:1883".  BTW, how do you know the connection is created?
