### ISSUE TITLE
Warning on createConnection

### ISSUE THREAD

**Issue by dukeak** [eclipse/ditto-examples#8]
Hi,

I get the following warning in the connectivity logs when I try to run a createConnection command with a payload mapping (exactly as in the example).

The log shows:

2019-03-07 16:25:56,390 WARN  [] o.e.d.s.c.m.m.MqttClientActor akka://ditto-cluster/system/sharding/connection/1/mqtt-example-connection-123/pa/$a/c1 - failed to start mapping processor due to org.eclipse.ditto.model.connectivity.MessageMapperConfigurationFailedException [message='The message mapper configuration failed due to: unterminated regular expression literal (incomingScript#1) - in line/column #1/539, source:
function mapToDittoProtocolMsg(headers, textPayload, bytePayload, contentType) {const jsonString = String.fromCharCode.apply(null, new Uint8Array(bytePayload));const jsonData = JSON.parse(jsonString); const thingId = jsonData.thingId; const value = { temp_sensor: { properties: { value: jsonData.temp } },altitude:        {            properties:            {                value: jsonData.alt            }        }    };    return Ditto.buildDittoProtocolMsg(my.test, thingId, things, twin, commands, modify, /features, headers, value);}', errorCode=connectivity:message.mapper.config.failed, statusCode=BAD_REQUEST, description='Check the configuration options of your mapper for errors.', href=null, dittoHeaders=ImmutableDittoHeaders [{}]]

**Comment by BobOntario** [comment]
![no index](https://user-images.githubusercontent.com/27965673/54001159-45591f80-4118-11e9-8905-d4c930473b2f.PNG)

**Comment by thjaeckle** [comment]
Hi.
Could you show how you did sent that command?
E.g. the cURL or postman call. Seems that some single quotes were missing in the contained mapping JS.

**Comment by dukeak** [comment]
I used the following CURL command:

curl -X POST 'http://localhost:8080/devops/piggyback/connectivity?timeout=10000' -u 'devops:foobar' -H'ditto:ditto' -H 'Content-Type: application/json' -d '{
    "targetActorSelection": "/system/sharding/connection",
    "headers": {
    	"aggregate": false
    },
    "piggybackCommand": {
        "type": "connectivity.commands:createConnection",
        "connection": {
            "id": "mqtt-example-connection-123",
            "connectionType": "mqtt",
            "connectionStatus": "open",
            "failoverEnabled": true,
            "uri": "tcp://test.mosquitto.org:1883",
            "sources": [{
                "addresses": ["ditto-tutorial/#"],
                "authorizationContext": ["nginx:ditto"],
                "qos": 0,
                "filters": []
            }],
            "targets": [{
                "address": "ditto-tutorial/{{ thing:id }}",
                "topics": [
                "_/_/things/twin/events",
                "_/_/things/live/messages"
                ],
                "authorizationContext": ["nginx:ditto"],
                "qos": 0
            }],
            "mappingContext": {
                "mappingEngine": "JavaScript",
                "options": {
                    "incomingScript": "function mapToDittoProtocolMsg(headers, textPayload, bytePayload, contentType) {const jsonString = String.fromCharCode.apply(null, new Uint8Array(bytePayload));const jsonData = JSON.parse(jsonString); const thingId = jsonData.thingId; const value = { temp_sensor: { properties: { value: jsonData.temp } },altitude:        {            properties:            {                value: jsonData.alt            }        }    };    return Ditto.buildDittoProtocolMsg('my.test', thingId, 'things', 'twin', 'commands', 'modify', '/features', headers, value);}"
                }
            }
        }
    }
}'

**Comment by dukeak** [comment]
I have escaped the single quotes by surrounding them wilh '\' which seems to result in them being maintained in the output. 

I now have a problem with the mqtt server closing the connection:

![image](https://user-images.githubusercontent.com/36761938/54031284-3de05780-41a6-11e9-9efd-4a0d45725991.png)

**Comment by thjaeckle** [comment]
Looks good now.
You configured "test.mosquitto.org" as MQTT endpoint. How do you publish a mqtt messages there?

You could try using `#` as source address just in order to check if you receive any messages at all - then you should get a lot (!) of messages from everyone using test.mosquitto.org.

Did you test the connection beforehand with a `"type": "connectivity.commands:testConnection",`?
As documented: https://www.eclipse.org/ditto/connectivity-manage-connections.html#test-connection
