### ISSUE TITLE
Does one connect support only one mappingContext?

### ISSUE THREAD

**Issue by haijunjiang** [eclipse/ditto-examples#9]
Hi: all

I have some defferent type of things in ditto, every thing has its own data structure.
So the mapingContext for these things are also different.
My question is can I use just one connection to support all type of things.
Thanks!

**Comment by thjaeckle** [comment]
Hi.
That's right, one connection does only supper one mapping context.
You can however use a single mapping context to map an arbitrary amount of different structures. Just put that in the Javascript code of the mapping context.
E.g. inspect the thing id and based on that (the type could be part of the ID) call the function which fits that ID.
